### ISSUE TITLE
Tweak package resolver

### ISSUE THREAD

**Issue by patcon** [mission-impossible-android/mission-impossible-android#57]
Currently, these things seem a little off:

- [ ] leaving [fdroid app](https://f-droid.org/repository/browse/?fdid=org.fdroid.fdroid) unpinned means we get test releases, eg `0.84-test`
- [ ] `--cpu` has no effect on fetched package, eg. [fdroid_fennec gets x86](https://f-droid.org/repository/browse/?fdid=org.mozilla.fennec_fdroid)

**Comment by SchnWalter** [comment]
The 1st item was fixed with the recent changes: https://github.com/mission-impossible-android/mission-impossible-android/blob/master/mia/templates/mia-default/settings.yaml#L51-L53

And I think that the 2nd item should be resolved with #53. Maybe we should just remove that `--cpu` option until we decide on how to actually use the templates.

**Comment by patcon** [comment]
I'd say that link is a work-around, but I thinking it should prob default to avoiding test unless explicitly chosen? Not sure. Seems pretty low priority anyhow :)

Actually, going to separate these, as the second is more important
