### ISSUE TITLE
Fix wget integration [Python 3]

### ISSUE THREAD

**Issue by SchnWalter** [mission-impossible-android/mission-impossible-android#82]
For some reason the wget integration (#68) worked just fine when I tested it. I downloaded new files, tried to see if you can continue an interrupted download and it did not give errors on files that have finished downloading. But it looks like there are several issues now; probably I had a different environment.

EDIT: Looks like this is an issue only in Python 3

**Comment by SchnWalter** [comment]
@patcon: now that we have a cache folder (#45) do we really need to use wget for downloading stuff? I think that it will be a lot of work on our side to properly deal with the output of wget in all the possible situations.

My opinion is that we should revert back to using the built in `urllib`. This way we won't need to handle all sort of exceptions like 'no disk space', 'request timeout' and other things that we don't take into account at the moment.

**Comment by patcon** [comment]
I'm open to it if we're hitting lots of edge cases, but I'm not sure I understand what the cache folder has to do with not using wget, as they seem unrelated.

I suspect the one you might be seeing (because I realized it after merging) is that wget has trouble with trying to resume a file when the remote file has changed (ie. `index.xml` changing daily), but that will be an issue with urllib as well, I suspect.

We were side-stepping this issue before anyhow, as we we just doing:

> does `resouces/blah.index.xml` exist? If no, download. if yes, skip.

But then we had a stale index.xml even 24 hours later, and no indication that anything was wrong. (`mia definition clean` was definitely overkill, so manual removal was what I was doing)

Regardless of using urllib or wget, I think we'll need some logic for checking the content length and overriding the existing file if it differs.

`wget` still strikes me as the better option, as we get 1) skipping of previously downloaded files, and 2) resumption of partial downloads, at very little effort. If we can get those easily with urllib (hopefully no more packages?), then I'd be a-ok with that too :)

Thoughts?

**Comment by SchnWalter** [comment]
Bloody index.xml: `it did not give errors on files that have finished downloading` :grin: 

Maybe we could just re-download the index.xml file if it is older than a couple of hours, and keep when it is newer.

Once we get #31 in we could use the hashes to check if an APK has been downloaded correctly before actually calling wget.

**Comment by patcon** [comment]
haha yeah, that "kill after x hours" thing sounds simple and totally functional :)
